
package Vista;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
/**
 *
 * @author MATHIAS
 */
public class MenuAlumnos extends javax.swing.JPanel {

    private Principal principal;
    
    public void mostrarPanel(JPanel panel) {
        panel.setSize(900, 680);
        panel.setLocation(0, 0);

        Contenido.setLayout(new BorderLayout());
        Contenido.removeAll();
        Contenido.add(panel, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }
    
    public MenuAlumnos(Principal principal) {
        this.principal = principal;
        initComponents();
        addRoundedPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelInformacion = new javax.swing.JPanel();
        TextoInformacion = new javax.swing.JLabel();
        PanelComunicados = new javax.swing.JPanel();
        TextoComunicados = new javax.swing.JLabel();
        PanelAsistencias = new javax.swing.JPanel();
        TextoAsistencias = new javax.swing.JLabel();
        PanelNotas = new javax.swing.JPanel();
        TextoNotas = new javax.swing.JLabel();
        PanelPagos = new javax.swing.JPanel();
        TextoPagos = new javax.swing.JLabel();
        PanelSalir = new javax.swing.JPanel();
        TextoSalir = new javax.swing.JLabel();
        jPanelLogo = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 680));

        jPanel1.setBackground(new java.awt.Color(0, 68, 129));

        PanelInformacion.setBackground(new java.awt.Color(0, 68, 129));
        PanelInformacion.setPreferredSize(new java.awt.Dimension(300, 42));

        TextoInformacion.setBackground(new java.awt.Color(0, 68, 129));
        TextoInformacion.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        TextoInformacion.setForeground(new java.awt.Color(151, 202, 219));
        TextoInformacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TextoInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumnos.png"))); // NOI18N
        TextoInformacion.setText("INFORMACIÓN");
        TextoInformacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextoInformacion.setIconTextGap(10);
        TextoInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextoInformacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextoInformacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextoInformacionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelInformacionLayout = new javax.swing.GroupLayout(PanelInformacion);
        PanelInformacion.setLayout(PanelInformacionLayout);
        PanelInformacionLayout.setHorizontalGroup(
            PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInformacionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TextoInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelInformacionLayout.setVerticalGroup(
            PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        PanelComunicados.setBackground(new java.awt.Color(0, 68, 129));

        TextoComunicados.setBackground(new java.awt.Color(0, 68, 129));
        TextoComunicados.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        TextoComunicados.setForeground(new java.awt.Color(151, 202, 219));
        TextoComunicados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TextoComunicados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informacion.png"))); // NOI18N
        TextoComunicados.setText("COMUNICADOS");
        TextoComunicados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextoComunicados.setIconTextGap(10);
        TextoComunicados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextoComunicadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextoComunicadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextoComunicadosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelComunicadosLayout = new javax.swing.GroupLayout(PanelComunicados);
        PanelComunicados.setLayout(PanelComunicadosLayout);
        PanelComunicadosLayout.setHorizontalGroup(
            PanelComunicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelComunicadosLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(TextoComunicados, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        PanelComunicadosLayout.setVerticalGroup(
            PanelComunicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoComunicados, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        PanelAsistencias.setBackground(new java.awt.Color(0, 68, 129));
        PanelAsistencias.setPreferredSize(new java.awt.Dimension(300, 42));

        TextoAsistencias.setBackground(new java.awt.Color(0, 68, 129));
        TextoAsistencias.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        TextoAsistencias.setForeground(new java.awt.Color(151, 202, 219));
        TextoAsistencias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TextoAsistencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salon-de-clases.png"))); // NOI18N
        TextoAsistencias.setText("ASISTENCIAS");
        TextoAsistencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextoAsistencias.setIconTextGap(10);
        TextoAsistencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextoAsistenciasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextoAsistenciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextoAsistenciasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelAsistenciasLayout = new javax.swing.GroupLayout(PanelAsistencias);
        PanelAsistencias.setLayout(PanelAsistenciasLayout);
        PanelAsistenciasLayout.setHorizontalGroup(
            PanelAsistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAsistenciasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TextoAsistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAsistenciasLayout.setVerticalGroup(
            PanelAsistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoAsistencias, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        PanelNotas.setBackground(new java.awt.Color(0, 68, 129));
        PanelNotas.setPreferredSize(new java.awt.Dimension(300, 42));

        TextoNotas.setBackground(new java.awt.Color(0, 68, 129));
        TextoNotas.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        TextoNotas.setForeground(new java.awt.Color(151, 202, 219));
        TextoNotas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TextoNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/notas.png"))); // NOI18N
        TextoNotas.setText("REPORTE DE NOTAS");
        TextoNotas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextoNotas.setIconTextGap(10);
        TextoNotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextoNotasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextoNotasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextoNotasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelNotasLayout = new javax.swing.GroupLayout(PanelNotas);
        PanelNotas.setLayout(PanelNotasLayout);
        PanelNotasLayout.setHorizontalGroup(
            PanelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNotasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TextoNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNotasLayout.setVerticalGroup(
            PanelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoNotas, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        PanelPagos.setBackground(new java.awt.Color(0, 68, 129));
        PanelPagos.setPreferredSize(new java.awt.Dimension(300, 42));

        TextoPagos.setBackground(new java.awt.Color(0, 68, 129));
        TextoPagos.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        TextoPagos.setForeground(new java.awt.Color(151, 202, 219));
        TextoPagos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TextoPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pagos.png"))); // NOI18N
        TextoPagos.setText("PAGOS");
        TextoPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextoPagos.setIconTextGap(10);
        TextoPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextoPagosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextoPagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextoPagosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelPagosLayout = new javax.swing.GroupLayout(PanelPagos);
        PanelPagos.setLayout(PanelPagosLayout);
        PanelPagosLayout.setHorizontalGroup(
            PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPagosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(TextoPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPagosLayout.setVerticalGroup(
            PanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoPagos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        PanelSalir.setBackground(new java.awt.Color(0, 68, 129));
        PanelSalir.setPreferredSize(new java.awt.Dimension(300, 42));

        TextoSalir.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        TextoSalir.setForeground(new java.awt.Color(151, 202, 219));
        TextoSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TextoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit-door.png"))); // NOI18N
        TextoSalir.setText("SALIR");
        TextoSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextoSalir.setIconTextGap(10);
        TextoSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextoSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextoSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextoSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelSalirLayout = new javax.swing.GroupLayout(PanelSalir);
        PanelSalir.setLayout(PanelSalirLayout);
        PanelSalirLayout.setHorizontalGroup(
            PanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSalirLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(TextoSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSalirLayout.setVerticalGroup(
            PanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jPanelLogo.setBackground(new java.awt.Color(0, 68, 129));
        jPanelLogo.setPreferredSize(new java.awt.Dimension(180, 180));

        jLabelLogo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AULA LOGO ofi.png"))); // NOI18N

        javax.swing.GroupLayout jPanelLogoLayout = new javax.swing.GroupLayout(jPanelLogo);
        jPanelLogo.setLayout(jPanelLogoLayout);
        jPanelLogoLayout.setHorizontalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLogoLayout.setVerticalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelAsistencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelComunicados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(PanelComunicados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelAsistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MarcaAula.png"))); // NOI18N

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1398, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextoNotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoNotasMouseClicked
        mostrarPanel(new NotasAlumno());
    }//GEN-LAST:event_TextoNotasMouseClicked

    private void TextoNotasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoNotasMouseEntered
        PanelNotas.setBackground(new Color(1, 138, 190));
    }//GEN-LAST:event_TextoNotasMouseEntered

    private void TextoNotasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoNotasMouseExited
        PanelNotas.setBackground(new Color(0, 68, 129));
    }//GEN-LAST:event_TextoNotasMouseExited

    private void TextoSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoSalirMouseClicked
        Principal log = new Principal();
        log.setSize(1200, 680);
        log.setLocationRelativeTo(null);
        log.setVisible(true);

        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        currentFrame.dispose();
    }//GEN-LAST:event_TextoSalirMouseClicked

    private void TextoSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoSalirMouseEntered
        PanelSalir.setBackground(new Color(1, 138, 190));
    }//GEN-LAST:event_TextoSalirMouseEntered

    private void TextoSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoSalirMouseExited
        PanelSalir.setBackground(new Color(0, 68, 129));
    }//GEN-LAST:event_TextoSalirMouseExited

    private void TextoAsistenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoAsistenciasMouseClicked
        mostrarPanel(new AsistenciaAlumno());
    }//GEN-LAST:event_TextoAsistenciasMouseClicked

    private void TextoAsistenciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoAsistenciasMouseEntered
        PanelAsistencias.setBackground(new Color(1, 138, 190));
    }//GEN-LAST:event_TextoAsistenciasMouseEntered

    private void TextoAsistenciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoAsistenciasMouseExited
        PanelAsistencias.setBackground(new Color(0, 68, 129));
    }//GEN-LAST:event_TextoAsistenciasMouseExited

    private void TextoPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoPagosMouseClicked
        //mostrarPanel(new AsistenciaAlumno());
    }//GEN-LAST:event_TextoPagosMouseClicked

    private void TextoPagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoPagosMouseEntered
        PanelPagos.setBackground(new Color(1, 138, 190));
    }//GEN-LAST:event_TextoPagosMouseEntered

    private void TextoPagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoPagosMouseExited
        PanelPagos.setBackground(new Color(0, 68, 129));
    }//GEN-LAST:event_TextoPagosMouseExited

    private void TextoComunicadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoComunicadosMouseClicked
        //Registro registro = new Registro(this); 
        //mostrarPanel(registro);
    }//GEN-LAST:event_TextoComunicadosMouseClicked

    private void TextoComunicadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoComunicadosMouseEntered
        PanelComunicados.setBackground(new Color(1, 138, 190));
    }//GEN-LAST:event_TextoComunicadosMouseEntered

    private void TextoComunicadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoComunicadosMouseExited
        PanelComunicados.setBackground(new Color(0, 68, 129));
    }//GEN-LAST:event_TextoComunicadosMouseExited

    private void TextoInformacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoInformacionMouseExited
        PanelInformacion.setBackground(new Color(0, 68, 129));
    }//GEN-LAST:event_TextoInformacionMouseExited

    private void TextoInformacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoInformacionMouseEntered
        PanelInformacion.setBackground(new Color(1, 138, 190));
    }//GEN-LAST:event_TextoInformacionMouseEntered

    private void TextoInformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoInformacionMouseClicked
        mostrarPanel(new InformaciónPersonalAlumno());
    }//GEN-LAST:event_TextoInformacionMouseClicked

    private void addRoundedPanel(){
        RoundedPanel roundedPanel = new RoundedPanel(30);
        roundedPanel.setBackground(new Color(151, 202, 219));
        roundedPanel.setPreferredSize(new java.awt.Dimension(180, 180));
        
        // Usamos GridBagLayout para centrar los componentes dentro del RoundedPanel
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        roundedPanel.setLayout(layout);
        
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.anchor = java.awt.GridBagConstraints.CENTER;
        roundedPanel.add(jLabelLogo, gbc); // Logo centrado
        
        // Añadir el RoundedPanel al jPanelLogo
        jPanelLogo.setLayout(new BorderLayout()); // Usar un layout adecuado en jPanelLogo
        jPanelLogo.add(roundedPanel, BorderLayout.CENTER);
        
        // Revalidar y repintar para actualizar la interfaz
        jPanelLogo.revalidate();
        jPanelLogo.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel PanelAsistencias;
    private javax.swing.JPanel PanelComunicados;
    private javax.swing.JPanel PanelInformacion;
    private javax.swing.JPanel PanelNotas;
    private javax.swing.JPanel PanelPagos;
    private javax.swing.JPanel PanelSalir;
    private javax.swing.JLabel TextoAsistencias;
    private javax.swing.JLabel TextoComunicados;
    private javax.swing.JLabel TextoInformacion;
    private javax.swing.JLabel TextoNotas;
    private javax.swing.JLabel TextoPagos;
    private javax.swing.JLabel TextoSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelLogo;
    // End of variables declaration//GEN-END:variables

    private void mostrarFrame(Registro registro) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
