/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.DatabaseUtils;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author MATHIAS
 */
public class NotasAdmin extends javax.swing.JPanel {

    /**
     * Creates new form Notas
     */
    public NotasAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFiltro = new javax.swing.JPanel();
        jLabelSalon = new javax.swing.JLabel();
        jLabelBimestre = new javax.swing.JLabel();
        jLabelCurso = new javax.swing.JLabel();
        jComboBimestre = new javax.swing.JComboBox<>();
        jComboCurso = new javax.swing.JComboBox<>();
        jTextFieldSalon = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(900, 680));

        jPanelFiltro.setBackground(new java.awt.Color(0, 27, 72));

        jLabelSalon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSalon.setForeground(new java.awt.Color(151, 202, 219));
        jLabelSalon.setText("SALON");

        jLabelBimestre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBimestre.setForeground(new java.awt.Color(151, 202, 219));
        jLabelBimestre.setText("BIMESTRE");

        jLabelCurso.setBackground(new java.awt.Color(151, 202, 219));
        jLabelCurso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCurso.setForeground(new java.awt.Color(151, 202, 219));
        jLabelCurso.setText("CURSO");

        jComboBimestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Bimestre I", "Bimestre II", "Bimestre III", "Bimestre IV" }));
        jComboBimestre.setActionCommand("");

        jComboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "MATEMÁTICAS", "COMUNICACIÓN", "CIENCIAS", "EDU. FÍSICA", "RELIGIÓN", "ARTE", "INGLES", "HISTORIA", "COMPUTACIÓN " }));
        jComboCurso.setActionCommand("");
        jComboCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCursoActionPerformed(evt);
            }
        });

        jButtonBuscar.setBackground(new java.awt.Color(255, 255, 51));
        jButtonBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(151, 202, 219));
        jButtonBuscar.setText("BUSCAR");
        jButtonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelFiltroLayout = new javax.swing.GroupLayout(jPanelFiltro);
        jPanelFiltro.setLayout(jPanelFiltroLayout);
        jPanelFiltroLayout.setHorizontalGroup(
            jPanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltroLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSalon)
                    .addComponent(jTextFieldSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBimestre)
                    .addComponent(jComboBimestre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCurso)
                    .addComponent(jComboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanelFiltroLayout.setVerticalGroup(
            jPanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltroLayout.createSequentialGroup()
                .addGroup(jPanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFiltroLayout.createSequentialGroup()
                        .addGroup(jPanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFiltroLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelBimestre)
                                    .addComponent(jLabelCurso)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFiltroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelSalon)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBimestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFiltroLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        scroll.setBackground(new java.awt.Color(1, 138, 190));
        scroll.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        table.setBackground(new java.awt.Color(222, 232, 241));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "APELLIDOS", "NOMBRES", "EX. MENSUAL", "EX. BIMESTRAL", "PROMEDIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(1, 138, 190));
        table.setSelectionBackground(new java.awt.Color(1, 138, 190));
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        scroll.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        //int row = table.getSelectedRow();
        //int column = table.getSelectedColumn();

        //String id = table.getValueAt(row, 0).toString();
        //jTextFieldId.setText(id);

        //String value = table.getValueAt(row, column).toString();
        //jTextFieldNota.setText(value);
        //esto no lo uses
    }//GEN-LAST:event_tableMouseClicked

    private int getBimestreNumber(String bimestre) {
        return switch (bimestre) {
            case "Bimestre I" -> 1;
            case "Bimestre II" -> 2;
            case "Bimestre III" -> 3;
            case "Bimestre IV" -> 4;
            default -> throw new IllegalArgumentException("Invalid bimestre: " + bimestre);
        };
    }

    private void jComboCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboCursoActionPerformed

    private void jButtonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseClicked
         String salon = jTextFieldSalon.getText(); 
        String bimestre = jComboBimestre.getSelectedItem().toString();
        String curso = jComboCurso.getSelectedItem().toString();

        int bimestreNumber = getBimestreNumber(bimestre);

        // Realiza la consulta a la base de datos
        try (Connection conn = DatabaseUtils.getConnection();
             Statement stmt = conn.createStatement()) {
            String query = "SELECT u.nombre AS nombre, u.apellido AS apellido, n.nota_mensual AS nota_mensual, " +
                    "n.nota_bimestral AS nota_bimestral, n.promedio AS promedio " +
                    "FROM Alumnos a " +
                    "JOIN Usuarios u ON a.alumno_id = u.usuario_id " +
                    "JOIN Notas n ON a.alumno_id = n.alumno_id " +
                    "JOIN Salones s ON a.salon_id = s.salon_id " +
                    "JOIN Bimestres b ON n.bimestre_id = b.ciclo_id " +
                    "JOIN Cursos c ON n.curso_id = c.curso_id " +
                    "WHERE s.nombre = '" + salon + "' AND c.nombre = '" + curso + "' AND b.bimestre = " + bimestreNumber;
            ResultSet rs = stmt.executeQuery(query);

            // Limpia la tabla actual
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);

            // Llena la tabla con los datos obtenidos
            while (rs.next()) {
                String apellidos = rs.getString("apellido");
                String nombres = rs.getString("nombre");
                String exMensual = rs.getString("nota_mensual");
                String exBimestral = rs.getString("nota_bimestral");
                String promedio = rs.getString("promedio");
                model.addRow(new Object[]{apellidos, nombres, exMensual, exBimestral, promedio});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButtonBuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBimestre;
    private javax.swing.JComboBox<String> jComboCurso;
    private javax.swing.JLabel jLabelBimestre;
    private javax.swing.JLabel jLabelCurso;
    private javax.swing.JLabel jLabelSalon;
    private javax.swing.JPanel jPanelFiltro;
    private javax.swing.JTextField jTextFieldSalon;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
